version: "3.9"

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery_worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge